### ISSUE TITLE
Blank connect wallet screen and can't click "connect wallet"

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#114]
~20% of the time I go to babylon.finance and click beta access it takes me to a blank connect wallet page (see below) and clicking "connect wallet" doesn't do anything.

If I then refresh page my wallet connects, my gardens page loads, and things work as expected.

<img width="1440" alt="Screen Shot 2021-06-17 at 1 42 12 PM" src="https://user-images.githubusercontent.com/1509695/122469589-fbf00f80-cf71-11eb-94fd-eb1adc9fe0a4.png">
<img width="1440" alt="Screen Shot 2021-06-17 at 1 43 45 PM" src="https://user-images.githubusercontent.com/1509695/122469723-1f1abf00-cf72-11eb-8c3d-d91e589fbb78.png">

**Comment by undfined** [comment]
This should now be fixed.
