### ISSUE TITLE
Withdrawing max leaves 2 DAI in garden

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#117]
Not sure if this is a bug or not, but I deposited 100 DAI then withdrew "max" DAI and I received 97.9 DAI, leaving 2.09 DAI in garden. From user perspective, I'd expect my deposits to be 0 after withdrawing the max amount.

https://etherscan.io/tx/0xfd7f6226d0b85d88596c2efd1f72e41d58f9808c01a540e2e783b1f4e86af584

<img width="1414" alt="Screen Shot 2021-06-17 at 2 06 50 PM" src="https://user-images.githubusercontent.com/1509695/122472334-4f179180-cf75-11eb-87cc-23a01e0498d8.png">

**Comment by rrecuero** [comment]
should be fixed after we do the new deploy
