### ISSUE TITLE
Small "connect wallet" button shows up after trying wallet connect

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#119]
Not sure this is intended? Doesn't show up when using metamask. 

<img width="1431" alt="Screen Shot 2021-06-18 at 6 54 57 AM" src="https://user-images.githubusercontent.com/1509695/122572107-44efa480-d002-11eb-921c-332244a1031a.png">

**Comment by rrecuero** [comment]
It should show as well in incognito mode or when you fully disconnect metamask.

Made it bigger
