### ISSUE TITLE
Wallet Connect connection modal keeps spinning, only way to view QR code is to refresh

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#120]
Reproduce:
- Go to homepage
- Click beta
- Wallet connect QR code pops up
- Close QR code
- Close error modal
- Try clicking either of the connect wallet buttons again
- Select Wallet Connect
- Connection modal spins forever
- If you then close spinning modal and try connecting wallet again, spinning modal returns
- If you refresh page QR code pops up (in this flow this is the only way to enter beta)

<img width="1439" alt="Screen Shot 2021-06-18 at 6 58 26 AM" src="https://user-images.githubusercontent.com/1509695/122573181-5c7b5d00-d003-11eb-8889-3d71a562b66f.png">
<img width="1440" alt="Screen Shot 2021-06-18 at 7 00 03 AM" src="https://user-images.githubusercontent.com/1509695/122573190-600ee400-d003-11eb-9868-3e887204c4e9.png">
<img width="1440" alt="Screen Shot 2021-06-18 at 7 00 27 AM" src="https://user-images.githubusercontent.com/1509695/122573202-63a26b00-d003-11eb-9aa2-ad1b1d6a80f3.png">
<img width="1440" alt="Screen Shot 2021-06-18 at 7 00 37 AM" src="https://user-images.githubusercontent.com/1509695/122573221-669d5b80-d003-11eb-9c0a-9d75583bbf2d.png">

**Comment by rrecuero** [comment]
Removing wallet connect
