### ISSUE TITLE
Can't connect to dapp via wallet connect (for first time users)

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#121]
NOTE: wallet connect works for metamask mobile + wallet connect if you have a metamask account that previously connected to babylon directly (e.g. via chrome extension). Neither metamask + wallet connect nor rainbow + wallet connect work for a new user flow (i.e. receiving gate and then trying to connect to beta).

Reproduce
- Scan QR code on Babylon with Wallet Connect (metamask or rainbow)
- Approve connection in wallet
- On Babylon side nothing happens
- Close QR code and see error message in modal (screenshots below)
- Refresh and QR code comes up again
- Confirmed in Rainbow and Metamask that the app was connected, but still couldn't enter Babylon

<img width="1004" alt="Screen Shot 2021-06-18 at 7 07 47 AM" src="https://user-images.githubusercontent.com/1509695/122574224-4cb04880-d004-11eb-865a-74079b00472d.png">

![IMG_8130](https://user-images.githubusercontent.com/1509695/122574521-939e3e00-d004-11eb-991b-c0d3e8671ba1.PNG)
![Uploading IMG_8129.PNG…]()

**Comment by rrecuero** [comment]
Removed wallet connect for the time being
