### ISSUE TITLE
Unclear how to withdraw your stake if a strategy is waiting for capital (could this result in capital being stuck in Garden?)

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#144]
If a strategy is waiting for capital due to a Garden being small, you can't withdraw your stake (because it's staked on the strategy) but you also can't delete the strategy. 

I could see this causing people to worry their capital is stuck indefinitely. 

How long will a strategy wait for capital? 

Should we give the strategist the option to delete the strategy while it's waiting for capital?

**Comment by rrecuero** [comment]
A strategy waits for a week max.

The strategist has this option already
