### ISSUE TITLE
If you cancel a transaction then try to do the same transaction again it shows the auto-populated amount in red despite it not being an error

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#151]
https://www.loom.com/share/d1d00c5e905b4727a212f0b259d0a8f8

**Comment by undfined** [comment]
Technically at the time this was invalid, since we were supposed to be disallowing withdrawal to 0. That has been fixed and I have a PR to drop the warning / validation. Let's double check this after that gets deployed.
