### ISSUE TITLE
Can't enter beta (loading forever) with strange errors (see screenshot)

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#153]

**Comment by chaseadam17** [comment]
<img width="1440" alt="Screen Shot 2021-06-29 at 2 58 55 PM" src="https://user-images.githubusercontent.com/1509695/123873019-b2e17900-d8ea-11eb-9c55-be85a56f6223.png">

**Comment by undfined** [comment]
@chaseadam17 Is this reliably reproducible or one off?

**Comment by chaseadam17** [comment]
It's reliably reproducible. Anytime I try to enter the My Gardens page with the wallet address below it happens. It doesn't happen with my other two addresses I use on Babylon.

Address: 0xBd1E66769eDD01260d947DC23658432d3195Cd9f
Using Chrome Version 91.0.4472.114 (Official Build) (arm64) and Metamask 9.6.1

Also happens in Brave and get similar errors, below

<img width="1440" alt="Screen Shot 2021-06-30 at 7 55 45 AM" src="https://user-images.githubusercontent.com/1509695/123983320-9ee45880-d978-11eb-8344-3489e43e12cd.png">
