### ISSUE TITLE
Depositing 100 DAI into Arkad's results in immediate loss of 0.32%

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#160]
This isn't urgent, but it's somewhat poor UX and we may want to fix at some point.

If I deposit 100 DAI into Arkad's Garden, immediately my "Deposits" are 100 DAI but my NAV is 99.67 with "Returns" of -0.32%. It's a small loss, but it's not the best welcome to a Garden to deposit and then see an immediate loss regardless the amount.

**Comment by rrecuero** [comment]
Not a bug. Gas costs of strategies. If there are no strategies, nav & deposits match
