### ISSUE TITLE
Does stake count as vote? Strategy went into cooldown without voting

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#162]
Created a strategy and staked 50 of my 100 DAI (only me and 100 DAI in garden). Strategy showed up under waiting for vote. However, I didn't vote.

I then closed Babylon and came back a few min later and strategy was in cooldown. I never voted for it. Is this intended? Does my stake count as my vote? Quorum is 10% and 1 steward is needed. 

Not sure if bug or not.

**Comment by rrecuero** [comment]
Stake counts as vote  -> multisig
