### ISSUE TITLE
Infinite loading error (not sure exactly how to repro)

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#163]

**Comment by chaseadam17** [comment]
Get stuck on loading screen. Not sure exactly how to repro. Might happen due to being idle on a Garden page for too long then navigating away? Will keep trying. Console errors below.

<img width="1440" alt="Screen Shot 2021-07-02 at 9 07 24 AM" src="https://user-images.githubusercontent.com/1509695/124301789-26ff6500-db15-11eb-826b-c23cf257d92f.png">

**Comment by undfined** [comment]
@chaseadam17 yep almost exactly right, basically the websocket connection to our provider is closed and it is not being reopened by ethers.js or provider so the socket just hangs. We have some code to try and manually force the reconnect but it's a bit messy. We'll take another look at it.
