### ISSUE TITLE
Blank screen on load (happens periodically but can't figure out exactly how to repro). "Can't read property 'timestamp' error"

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#170]

**Comment by chaseadam17** [comment]
<img width="1438" alt="Screen Shot 2021-07-05 at 8 57 46 AM" src="https://user-images.githubusercontent.com/1509695/124498151-c0768300-dd70-11eb-8ce3-d9e12214f46e.png">

**Comment by rrecuero** [comment]
https://sentry.io/organizations/babylonfinance/issues/2495328375/?project=5732012&query=is%3Aunresolved
