### ISSUE TITLE
Return on mygardens appears to be calculated using all-time deposits instead of current deposits

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#171]

**Comment by chaseadam17** [comment]
<img width="1440" alt="Screen Shot 2021-07-05 at 9 10 47 AM" src="https://user-images.githubusercontent.com/1509695/124498321-ff0c3d80-dd70-11eb-9425-66e571a2ba43.png">

**Comment by rrecuero** [comment]
Not an Issue. This only happens to the old users because of the contributor bug we had at the beginning
