### ISSUE TITLE
Return on strategies red dot appears to be broken

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#172]

**Comment by chaseadam17** [comment]
Unclear what we're trying to show here. Location also seems a bit odd. 

<img width="1440" alt="Screen Shot 2021-07-05 at 9 22 44 AM" src="https://user-images.githubusercontent.com/1509695/124499290-a047c380-dd72-11eb-8e4c-0b50c037b2e4.png">

**Comment by rrecuero** [comment]
Duplicate of 168
