### ISSUE TITLE
Switching wallet gets user stuck in garden creation flow due to inactive approval button

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#177]

**Comment by chaseadam17** [comment]
Steps to reproduce:

- Use Babylon using one metamask address
- Switch to another address that has already approved garden creation
- You will be unable to create a garden due to inactive "approved" button

Seems like a bug with how we're updating whether an address has approved a tx. Hard refreshing seems to fix.

Related: I already approved with these addresses. Do I need to do again because we made changes to the protocol?

<img width="1276" alt="Screen Shot 2021-07-06 at 8 38 05 AM" src="https://user-images.githubusercontent.com/1509695/124628831-b66a8800-de35-11eb-8548-3c5074c08795.png">

**Comment by chaseadam17** [comment]
Another related issue:

If you hard refresh it lets you approve. Then after approving if you click create garden and reject in your wallet, you land back on the same modal above where there is an inactive approved! button and you are stuck.

**Comment by undfined** [comment]
Ok a few thoughts on this one...

1) I think if a user rejects a TX our / their lives will be simpler if we close / clear the submission modal. Might be annoying but the alternative is hard to reason about. In the specific case where you approved / clicked create / then rejected, I _think_ I can do something smart but no promises.

2) Switching wallets in the middle of multi-step TX is also a pain. We can't control the MetaMask layer so we can't do something like are you sure you want to change wallets caveats blah blah... Wonder if we want to just again clear the modal/state and they have to start over. It's hard to reason about resetting state in the middle of a multi-step submission of this form. 

> Related: I already approved with these addresses. Do I need to do again because we made changes to the protocol?

3) Not sure on this multiple approvals required issue. @ylv-io Does this seem plausible?
