### ISSUE TITLE
User can't see all gardens they've been invited to on my gardens page

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#190]
NMTSavant — Today at 11:23 AM
An edge case with someone receiving multiple garden invites and not depositing into them immediately. Someone who gets an invite to Garden A but does not deposit into it, then gets an invite into Garden B, can only see a Garden A invite message on the /me page. They have to visit Garden B's page directly before /me works to view both gardens.

**Comment by rrecuero** [comment]
They just need to click on the button on the welcome page to dismiss the welcome
