### ISSUE TITLE
Appears to be share price bug in Garden graph

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#20]
Expected behavior: a Garden with no strategies would have a share price equal to reserve asset benchmark price.

Actual behavior: share price appears to have plummeted, due to both the color (red) and the line going down, despite no strategies in the Garden. It's also the only place we talk about share price, which is sort of confusing. Everywhere else we prioritize talking about NAV and returns.

Possible fix: I think users likely want to see the Garden returns over time (similar to how robinhood plots your portfolio, dHedge shows performance, etc.). Would it be possible to just plot the $ or % returns in the graph?

Later we could add the ability to plot the benchmark asset, change the benchmark asset, plot strategy returns, etc. Idk, just spitballing, I know it's likely a pretty complex problem.

<img width="1375" alt="Screen Shot 2021-06-04 at 3 33 02 PM" src="https://user-images.githubusercontent.com/1509695/120869614-b253fd80-c54b-11eb-9bc5-2cf13fc22dfe.png">

**Comment by undfined** [comment]
I'm guessing this was an anomaly since it is no longer reproducible. If we see this again I will reopen.
