### ISSUE TITLE
Deposit modal doesn't load

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#21]
About 10% of the times I click "Add Funds" the deposit modal only half loads (see screenshot below).

If I reload page it tends to work. Not exactly sure how to reproduce every time yet, will keep trying. 

<img width="1438" alt="Screen Shot 2021-06-04 at 3 46 20 PM" src="https://user-images.githubusercontent.com/1509695/120869862-3c03cb00-c54c-11eb-88fb-9120b6ec1485.png">

**Comment by undfined** [comment]
It's loading, but very slowly. Basically JsonRpcProvider from ethers is a dog, and makes way too many async requests in the browser and blocks some of the important calls (ie: the ones need to render the deposit modal). Switching back to WebSocketProvider will fix this.
