### ISSUE TITLE
Create GetTally account with photo but Babylon doesn't update to it from my address

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#211]
I've been digging and I think this is a problem on Tallys end. There are a bunch of bugs around linking the wallet address to an account. I've contacted their support and would hold off on our end until I hear back

**Comment by chaseadam17** [comment]
<img width="1440" alt="Screen Shot 2021-07-22 at 3 25 25 PM" src="https://user-images.githubusercontent.com/1509695/126717046-6ce15e43-c5b7-42c7-9f8b-f1072fe3185d.png">
<img width="1440" alt="Screen Shot 2021-07-22 at 3 25 13 PM" src="https://user-images.githubusercontent.com/1509695/126717051-c322c5fa-6f1e-4c9a-a7eb-27397c943a95.png">

**Comment by undfined** [comment]
Correct, this is a Tally issue IMO. We can reach out to Raf about this.

**Comment by undfined** [comment]
@chaseadam17 have you heard back here? I can put you in touch with Raf directly if you want to expedite.
