### ISSUE TITLE
Garden leaderboard occasionally shows no members

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#213]

**Comment by chaseadam17** [comment]
<img width="1440" alt="Screen Shot 2021-07-22 at 4 09 10 PM" src="https://user-images.githubusercontent.com/1509695/126720445-139c413f-b080-4974-8558-603cff113d9f.png">

**Comment by chaseadam17** [comment]
its doing this for all gardens, even arkad's. can't figure out exactly how to reproduce but it happens pretty often.

**Comment by chaseadam17** [comment]
i think it has to do with switching your wallet address then navigating to my gardens then entering a garden. if you refresh it then loads the leaderboard. so something to do with wallet switch.

**Comment by rrecuero** [comment]
Some gardens are missing the leaderboard, it's because of the event change
