### ISSUE TITLE
Can't withdraw full amount of principal from a garden, confusion around what can be withdrawn, unexpectedly high gas upon second withdraw

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#221]
This seems like an important one. Worth watching the video. It encompasses three issues:

1. A user can't seem to withdraw their full amount of tokens from a Garden. It leaves a pretty big balance.
2. There seems to be some confusion around how we report what a user can withdraw
3. Weird unexpected gas surge (strange because withdrawing a second time was like 5x more expensive than before and there are no strategies in the garden)

Video: https://www.loom.com/share/92c9e744aac44fd79a5653b330f591c9

**Comment by rrecuero** [comment]
Fixed https://github.com/babylon-finance/dapp/pull/458

**Comment by rrecuero** [comment]
Fixed https://github.com/babylon-finance/dapp/pull/458
