### ISSUE TITLE
Litepaper and Documentation links aren't showing up in the dapp nav (only on website)

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#229]
<img width="820" alt="Screen Shot 2021-07-28 at 11 52 58 AM" src="https://user-images.githubusercontent.com/1509695/127379741-313c9f77-ecc8-4503-a1d3-d7931b821d7c.png">

**Comment by chaseadam17** [comment]
<img width="1440" alt="Screen Shot 2021-07-26 at 1 46 59 PM" src="https://user-images.githubusercontent.com/1509695/127056950-db3be0cc-eab8-4a4f-9788-dbeee56e02bd.png">

**Comment by chaseadam17** [comment]
Users are also requesting this: 

<img width="827" alt="Screen Shot 2021-07-28 at 11 45 24 AM" src="https://user-images.githubusercontent.com/1509695/127378698-0731e390-03c1-402c-9876-58f7a8952d2d.png">

**Comment by undfined** [comment]
Sounds good, this was an intentional change :P Let's discuss in product sync what we want up there.

**Comment by undfined** [comment]
These are now in the footer within the dapp, I think is the a good middle ground as users are accustomed to looking in the footer for informational links. Closing for now and we can revisit if reports come from users.
