### ISSUE TITLE
Unknown pool showing up in High-R LP garden

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#257]
<img width="1257" alt="Screen Shot 2021-07-30 at 2 22 47 PM" src="https://user-images.githubusercontent.com/1509695/127712832-67b88745-bcf7-4f86-8c06-17e2f0858d2d.png">

**Comment by undfined** [comment]
This looks to be fixed, either we failed to fetch the link-weth token data from a tokenlist or we didn't have it but I've tested and it renders correctly now.
