### ISSUE TITLE
Infinite loading when checking if an asset is valid

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#272]
User reported this: 

<img width="519" alt="Screen Shot 2021-08-03 at 8 13 36 AM" src="https://user-images.githubusercontent.com/1509695/128040432-08dfd7a3-14c9-4a55-8495-4e0a9b7368be.png">

I was able to reproduce:
- Stable Garden
- Try to long weth
- Get infinite loading with following console error

<img width="1440" alt="Screen Shot 2021-08-03 at 8 12 13 AM" src="https://user-images.githubusercontent.com/1509695/128040523-6a476137-47d7-4aa4-aebb-d8ce0fd7a2d0.png">
<img width="998" alt="Screen Shot 2021-08-03 at 8 11 59 AM" src="https://user-images.githubusercontent.com/1509695/128040532-b45cb44d-adc4-4af1-bde5-61a4167870db.png">

**Comment by undfined** [comment]
@ylv-io looking into this, failing on chain since the directional comparison of WETH to DAI is "invalid".
