### ISSUE TITLE
Spacing issues in viewport / footer / MyGardens

### ISSUE THREAD

**Issue by undfined** [babylon-finance/issues#28]
GardenDetailPage:
![image](https://user-images.githubusercontent.com/954432/120898842-a1ee6200-c5e1-11eb-8443-bca95da9a460.png)

MyGardens (loading):
![image](https://user-images.githubusercontent.com/954432/120898866-b92d4f80-c5e1-11eb-895d-dce52f12d57a.png)

**Comment by rrecuero** [comment]
this only seems to be an issue with big screens. I think I fixed it but I cannot test it
