### ISSUE TITLE
My % Return is different on homepage and Garden page

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#29]
It seemed odd that my % return was -0.06% in the Garden but 0% on homepage. Possibly due to rounding or something?
<img width="1437" alt="Screen Shot 2021-06-07 at 8 29 33 AM" src="https://user-images.githubusercontent.com/1509695/121046923-f709af80-c76a-11eb-9bc3-3725cbf899b1.png">
<img width="1440" alt="Screen Shot 2021-06-07 at 8 28 54 AM" src="https://user-images.githubusercontent.com/1509695/121046960-f96c0980-c76a-11eb-9a48-40505a2bd171.png">

**Comment by undfined** [comment]
Looks like small rounding differences, we'll take a look.

**Comment by undfined** [comment]
@chaseadam17 Merged a fix to avoid rounding decimals in many places, let me know if this is still and issue and we can reopen.
