### ISSUE TITLE
Application loading gif freezes for ~10 seconds before page loads

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#30]
Not sure if others experience this or not, but I'm on Chrome Version 91.0.4472.77 (Official Build) (arm64) and it does this about 20% of the time. It seems like a freeze but then after 10 or so seconds it loads.

**Comment by rrecuero** [comment]
closing it for now

**Comment by chaseadam17** [comment]
Just happened again and page never loaded. Seems quite common. Error message below.

<img width="562" alt="Screen Shot 2021-06-07 at 12 10 57 PM" src="https://user-images.githubusercontent.com/1509695/121075284-d8ff7780-c789-11eb-8346-53d570d29334.png">

**Comment by chaseadam17** [comment]
Happened again but with nothing on screen this time. 

<img width="1439" alt="Screen Shot 2021-06-07 at 12 29 58 PM" src="https://user-images.githubusercontent.com/1509695/121077179-2d0b5b80-c78c-11eb-8c94-9ff7d54e3a23.png">

**Comment by chaseadam17** [comment]
<img width="588" alt="Screen Shot 2021-06-07 at 12 32 36 PM" src="https://user-images.githubusercontent.com/1509695/121077434-79569b80-c78c-11eb-94b7-3388231a5fdb.png">

**Comment by undfined** [comment]
FYI: In the blocknative discord discussion now. Will report back asap.
