### ISSUE TITLE
Click TOS then close and reopen deposit modal and you can deposit without clicking TOS (and clicking deactivates deposit button)

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#34]
Steps to repro:
1. Click "Deposit to Join Garden"
2. Enter amount and click TOS checkbox
3. Close modal
4. Reopen modal and the deposit button is active despite TOS not being clicked and if you click the TOS checkbox the deposit button deactivates
5. If you then uncheck TOS and click deposit, it allows you to complete your deposit without agreeing to TOS

<img width="789" alt="Screen Shot 2021-06-07 at 7 02 49 PM" src="https://user-images.githubusercontent.com/1509695/121111179-48de2400-c7c3-11eb-9576-dc3b312aef75.png">
<img width="681" alt="Screen Shot 2021-06-07 at 7 02 42 PM" src="https://user-images.githubusercontent.com/1509695/121111186-4b407e00-c7c3-11eb-98ee-6355fdd01bc5.png">

**Comment by rrecuero** [comment]
Fixed
