### ISSUE TITLE
Depositing ETH in ETH test garden results in an immediate % return of -1.76%

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#35]
This might have the same underlying cause as my other issue (% return is different on my garden page and the garden page), but it's different from a UX perspective so adding it anyways.

Expected behavior: Immediately upon depositing into a Garden that has no active Strategies I would expect no return.

Actual behavior: Immediately upon depositing I have a return of -1.76%, which is startling as a user and makes me wonder how / why I lost money so rapidly, especially given that there are no active Strategies and the performance graph is flat (there is one in cooldown).

<img width="1439" alt="Screen Shot 2021-06-07 at 7 08 16 PM" src="https://user-images.githubusercontent.com/1509695/121111686-2f89a780-c7c4-11eb-8559-1e0c2bc434e3.png">

<img width="1039" alt="Screen Shot 2021-06-07 at 7 13 23 PM" src="https://user-images.githubusercontent.com/1509695/121111906-88594000-c7c4-11eb-9200-9729f7b2bdcb.png">

**Comment by undfined** [comment]
@rrecuero could this be because we the user had to pay tx cost to swap into WETH?

**Comment by rrecuero** [comment]
This along with a frontend PR will fix it https://github.com/babylon-finance/protocol/pull/356
