### ISSUE TITLE
If you enter a valid estimated return during strategy creation, then close modal and submit another strategy, the amount you entered is there but "next" is disabled

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#36]
Steps to repro:
1. Submit strategy
2. Enter name and operations and click next
3. Defaults load but next button is disabled
4. If you delete 1 day expected duration and then re-enter 1, the button is enabled

<img width="1280" alt="Screen Shot 2021-06-07 at 7 38 21 PM" src="https://user-images.githubusercontent.com/1509695/121114264-47632a80-c7c8-11eb-878d-c4aa7c13ae81.png">
<img width="1277" alt="Screen Shot 2021-06-07 at 7 41 20 PM" src="https://user-images.githubusercontent.com/1509695/121114335-606bdb80-c7c8-11eb-94b0-e63946e30078.png">

**Comment by rrecuero** [comment]
Can't repro @chaseadam17 . Actually expected return should start as not filled

**Comment by chaseadam17** [comment]
I figured it out. If you enter a valid amount into the expected return, then close the strategy modal and re-open, the amount you entered is still there but the button is disabled as if the amount is no longer valid.

**Comment by rrecuero** [comment]
Fixed
