### ISSUE TITLE
Vote signing is broken for hardware wallets

### ISSUE THREAD

**Issue by undfined** [babylon-finance/issues#4]
Steps to repro: 
- Join garden
- View candidates
- Click upvote/downvote
- Attempt to sign vote in Metamask w/hardware wallet
- No verification occurs in connected device

Expected:
- Connected device triggers verification and signature is sent upon "Verify"

**Comment by chaseadam17** [comment]
This is broken for non hardware wallets too (i.e. with Metamask in Chrome). Want me to create a separate issue for this or should we incorporate it here?

**Comment by undfined** [comment]
Already deployed a fix for non-hardware :)
