### ISSUE TITLE
WebsocketProvider is unstable causing app to "stall" occasionally

### ISSUE THREAD

**Issue by undfined** [babylon-finance/issues#40]
Stack includes this when it happens: `websocket-provider.ts:203 WebSocket is already in CLOSING or CLOSED state.`

**Comment by rrecuero** [comment]
Cannot be solved for now https://github.com/ethers-io/ethers.js/pull/1622/files

**Comment by rrecuero** [comment]
https://github.com/babylon-finance/dapp/pull/328
