### ISSUE TITLE
Transport status error: ledger device: UNKNOWN ERROR (0x6b0c) during withdrawal

### ISSUE THREAD

**Issue by undfined** [babylon-finance/issues#41]
WETH Test Garden

windows 10 pro
chrome 90.0.4430.212 (Official Build) (64-bit) (cohort: Stable)

![image](https://user-images.githubusercontent.com/954432/121222658-98603680-c83b-11eb-8cdd-ba56690bbade.png)

**Comment by rrecuero** [comment]
I think this was caused by the previous error. Victor couldn't repro again
