### ISSUE TITLE
From Lars: Could not see Yearn V2 vaults in strategy creation

### ISSUE THREAD

**Issue by rrecuero** [babylon-finance/issues#49]
**Describe the bug**
Yearn V2 Vaults are not listed and some of the v1 vaults are missing.

**To Reproduce**
1. Go to 'A garden'
2. Click on 'Submit Strategi.'
3. Select Yield Farming -> Yearn.
4. See no Yearn V2 vaults

**Expected behavior**
"Was just looking at adding a strategy for yearn and it seems its not picking all vaults and the ones that are picked up are v1?"

**Comment by ylv-io** [comment]
Yearn is pointing to the v1 registry. Should use v2 registry instead.
https://etherscan.io/address/0xfeb4acf3df3cdea7399794d0869ef76a6efaff52
https://docs.yearn.finance/developers/deployed-contracts-registry
