### ISSUE TITLE
Blank screen before loading screen shows up, perhaps due to metamask?

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#50]
Strange loading sequence. See video below and console screenshot.

https://user-images.githubusercontent.com/1509695/121267402-fd824f00-c870-11eb-9ec1-3f7dea379554.mp4

<img width="558" alt="Screen Shot 2021-06-08 at 3 34 37 PM" src="https://user-images.githubusercontent.com/1509695/121267445-0c690180-c871-11eb-9f98-8089ab6c83a4.png">

Stack trace:

Line wrap
--
&nbsp; | &lt;!doctype html&gt;&lt;html lang="en"&gt;&lt;head&gt;&lt;meta charset="utf-8"/&gt;&lt;meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=3,user-scalable=yes,minimal-ui"/&gt;&lt;meta name="description" content=""/&gt;&lt;link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/&gt;&lt;link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/&gt;&lt;link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/&gt;&lt;link rel="mask-icon" href="/safari-pinned-tab.svg" color="#917dff"/&gt;&lt;meta name="msapplication-TileColor" content="#160e6b"/&gt;&lt;meta name="theme-color" content="#160E6B"/&gt;&lt;link rel="manifest" href="/site.webmanifest"/&gt;&lt;title&gt;Babylon.finance&lt;/title&gt;&lt;link href="/static/css/11.6e462b63.chunk.css" rel="stylesheet"&gt;&lt;link href="/static/css/main.6db1bc98.chunk.css" rel="stylesheet"&gt;&lt;/head&gt;&lt;body&gt;&lt;noscript&gt;You need to enable JavaScript to run this app.&lt;/noscript&gt;&lt;script&gt;window.intercomSettings={app_id:"nisjkd1k"}&lt;/script&gt;&lt;script&gt;!function(){var t=window,e=t.Intercom;if("function"==typeof e)e("reattach_activator"),e("update",t.intercomSettings);else{var n=document,a=function(){a.c(arguments)};a.q=[],a.c=function(t){a.q.push(t)},t.Intercom=a;var c=function(){var t=n.createElement("script");t.type="text/javascript",t.async=!0,t.src="https://widget.intercom.io/widget/nisjkd1k";var e=n.getElementsByTagName("script")[0];e.parentNode.insertBefore(t,e)};t.attachEvent?t.attachEvent("onload",c):t.addEventListener("load",c,!1)}}()&lt;/script&gt;&lt;div id="root"&gt;&lt;form name='lander-subscribe' hidden method='post'&gt;&lt;input type='hidden' name='form-name' value='lander-subscribe' /&gt;&lt;input type="email" name="email"/&gt;&lt;/form&gt;&lt;/div&gt;&lt;script&gt;!function(e){function r(r){for(var n,f,c=r[0],u=r[1],i=r[2],d=0,l=[];d&lt;c.length;d++)f=c[d],Object.prototype.hasOwnProperty.call(o,f)&amp;&amp;o[f]&amp;&amp;l.push(o[f][0]),o[f]=0;for(n in u)Object.prototype.hasOwnProperty.call(u,n)&amp;&amp;(e[n]=u[n]);for(b&amp;&amp;b(r);l.length;)l.shift()();return a.push.apply(a,i\|\|[]),t()}function t(){for(var e,r=0;r&lt;a.length;r++){for(var t=a[r],n=!0,c=1;c&lt;t.length;c++){var u=t[c];0!==o[u]&amp;&amp;(n=!1)}n&amp;&amp;(a.splice(r--,1),e=f(f.s=t[0]))}return e}var n={},o={10:0},a=[];function f(r){if(n[r])return n[r].exports;var t=n[r]={i:r,l:!1,exports:{}};return e[r].call(t.exports,t,t.exports,f),t.l=!0,t.exports}f.e=function(e){var r=[],t=o[e];if(0!==t)if(t)r.push(t[2]);else{var n=new Promise((function(r,n){t=o[e]=[r,n]}));r.push(t[2]=n);var a,c=document.createElement("script");c.charset="utf-8",c.timeout=120,f.nc&amp;&amp;c.setAttribute("nonce",f.nc),c.src=function(e){return f.p+"static/js/"+({}[e]\|\|e)+"."+{0:"39f6fb12",1:"e0e280f5",2:"877117c2",3:"720d958f",4:"ef948b1f",5:"1d86e349",6:"7dc25150",7:"cbdc4153",8:"a6833a07",12:"e122ca27",13:"3dfc389a",14:"91c0b85c",15:"81a5f05e",16:"949d38ba",17:"5b011c7b",18:"915ee772",19:"cab33581",20:"9a07a4b7",21:"1da943f4",22:"ac2efb7c",23:"a7ae622d",24:"c585a6d9",25:"f746c072",26:"7eae32c1",27:"baf054f4",28:"72eba1e2",29:"2256f081",30:"f9defd03",31:"2d22323d",32:"20b60178",33:"b5d625c1",34:"4cd07b5c",35:"6d20f7ee",36:"f1470145",37:"5566d5f6",38:"dfb9e02b",39:"1021bb31",40:"0d5cb971",41:"084c0660",42:"23d19b36",43:"f4f6a134",44:"2954a98a",45:"c0a70423",46:"68917104",47:"e5bb8501",48:"ae1c8586",49:"e1d9ed28",50:"88f61504",51:"e99b294f",52:"3872b877",53:"be1f6b80",54:"8088041f",55:"e47a3358",56:"2fb2fe13",57:"856403c5",58:"e931d17b",59:"ef80df21",60:"9b99b3d9",61:"7b95e122",62:"39b307b8",63:"43352f01",64:"430753de"}[e]+".chunk.js"}(e);var u=new Error;a=function(r){c.onerror=c.onload=null,clearTimeout(i);var t=o[e];if(0!==t){if(t){var n=r&amp;&amp;("load"===r.type?"missing":r.type),a=r&amp;&amp;r.target&amp;&amp;r.target.src;u.message="Loading chunk "+e+" failed.\n("+n+": "+a+")",u.name="ChunkLoadError",u.type=n,u.request=a,t[1](u)}o[e]=void 0}};var i=setTimeout((function(){a({type:"timeout",target:c})}),12e4);c.onerror=c.onload=a,document.head.appendChild(c)}return Promise.all(r)},f.m=e,f.c=n,f.d=function(e,r,t){f.o(e,r)\|\|Object.defineProperty(e,r,{enumerable:!0,get:t})},f.r=function(e){"undefined"!=typeof Symbol&amp;&amp;Symbol.toStringTag&amp;&amp;Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},f.t=function(e,r){if(1&amp;r&amp;&amp;(e=f(e)),8&amp;r)return e;if(4&amp;r&amp;&amp;"object"==typeof e&amp;&amp;e&amp;&amp;e.__esModule)return e;var t=Object.create(null);if(f.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&amp;r&amp;&amp;"string"!=typeof e)for(var n in e)f.d(t,n,function(r){return e[r]}.bind(null,n));return t},f.n=function(e){var r=e&amp;&amp;e.__esModule?function(){return e.default}:function(){return e};return f.d(r,"a",r),r},f.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},f.p="/",f.oe=function(e){throw console.error(e),e};var c=this["webpackJsonp@babylon-finance/dapp"]=this["webpackJsonp@babylon-finance/dapp"]\|\|[],u=c.push.bind(c);c.push=r,c=c.slice();for(var i=0;i&lt;c.length;i++)r(c[i]);var b=u;t()}([])&lt;/script&gt;&lt;script src="/static/js/11.54293fd7.chunk.js"&gt;&lt;/script&gt;&lt;script src="/static/js/main.843b2d00.chunk.js"&gt;&lt;/script&gt;&lt;/body&gt;&lt;/html&gt;

**Comment by undfined** [comment]
It's just a momentary delay in rendering the loader overtop of the base background color. Not sure why, but we will look into it.

**Comment by rrecuero** [comment]
https://github.com/babylon-finance/dapp/pull/325

**Comment by rrecuero** [comment]
Fixed
