### ISSUE TITLE
`minRebalanceCapital` is ignore during strategy creation for WETH Garden.

### ISSUE THREAD

**Issue by ylv-io** [babylon-finance/issues#51]
I've created a strategy in the WETH garden with `minRebalanceCapital` value set to `0.1` and it was ignored and default value of 5.0 WETH is used instead.

**Comment by undfined** [comment]
This looks to be true for all "Advanced" params in Strategy submission and also causes weird behavior in the Duration and Expected Return fields. I haven't gotten to the bottom of it but it has to do with the Number values being set to strings in the dispatch action.

**Comment by rrecuero** [comment]
https://github.com/babylon-finance/dapp/pull/330
