### ISSUE TITLE
Braven: User can't make deposit

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#52]
From Discord:

"Trying to break the system with random deposits
Sorry the message is not more clear but it's all I could see on my end
https://jmp.sh/12fuv3d

This is the error in Sentry in case you can see it on your end:

https://o577344.ingest.sentry.io/api/5732012/envelope/?sentry_key=dc74338b7a2a45f282939675e833dcb6&sentry_version=7

**Comment by undfined** [comment]
This looks like the transaction was sent correctly and that the user is waiting on it to be confirmed (mined) on chain. Can you grab the wallet address @chaseadam17 so we can see details?

**Comment by undfined** [comment]
Also, that sentry error is unrelated and likely due to uBlock or similar.

**Comment by rrecuero** [comment]
This doesn't look like an error. He just needs to wait until it is mined? We need the transaction id @chaseadam17

**Comment by chaseadam17** [comment]
Assuming you don't need transaction id because this is closed? If you still
need it lmk and I'll ask Raul to see if he can find it.
