### ISSUE TITLE
Site didn't load with Brave (loading forever)

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#56]
Went to babylon.finance/me. Switched account in Metamask. Loading gif came up and laster for a long time.

<img width="576" alt="Screen Shot 2021-06-09 at 12 12 31 PM" src="https://user-images.githubusercontent.com/1509695/121415066-30cde800-c91c-11eb-954d-dfe1d42aaef8.png">

**Comment by undfined** [comment]
Is this "always" or was it a specific instance?

**Comment by chaseadam17** [comment]
Specific instance. I just tried again and it worked. Tried to repro but couldn't. Will try specifics steps to repro if it happens again.

**Comment by undfined** [comment]
I think we know the issue and it has to do with instability of Websockets and reconnect. @rrecuero is looking into this.

**Comment by rrecuero** [comment]
I already sent a fix that tries to reconnect every 5 seconds
