### ISSUE TITLE
During Garden creation if you don't have DAI in wallet then add DAI to wallet deposit amount still shows up as red

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#60]
During Garden creation review my default deposit of 100 DAI is red, likely due to there not being enough DAI in my wallet (it's not clear why it's red and this may confuse users, but likely not a top priority fix).

If I add DAI to my wallet (via Metamask swap) the amount of DAI is still red, although the approval required button is now active. The DAI input should no longer be red.

<img width="1434" alt="Screen Shot 2021-06-09 at 12 40 23 PM" src="https://user-images.githubusercontent.com/1509695/121419002-5b21a480-c920-11eb-882e-468eead657d3.png">

**Comment by undfined** [comment]
I'm not sure we want to handle this case. I think the user should start over as this is going to get very complicated to keep state in sync. @rrecuero what do you think?
