### ISSUE TITLE
Can click "Create Garden" without entering any deposit amount

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#62]
This might have to do with the bug of my wallet not having DAI then adding DAI to wallet. However...

To repro:
1. Create DAI Garden with a wallet without DAI
2. On review screen swap DAI into wallet
3. Enter 100 DAI deposit
4. Approve
5. You can now click to create the garden without entering any DAI, but the modal refreshes

<img width="1440" alt="Screen Shot 2021-06-09 at 1 10 56 PM" src="https://user-images.githubusercontent.com/1509695/121422801-6ecf0a00-c924-11eb-9a46-6647ddeef141.png">

https://user-images.githubusercontent.com/1509695/121422815-72fb2780-c924-11eb-9ec3-bb2b33143587.mp4

**Comment by chaseadam17** [comment]
I just tested this again and it is not due to the wallet not having DAI issue. It appears anytime you create a garden you can click "create garden" without entering any deposit amount.

**Comment by rrecuero** [comment]
https://github.com/babylon-finance/dapp/pull/332
