### ISSUE TITLE
Can approve a DAI deposit without agreeing to terms and without enough DAI in my wallet

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#65]
This is when depositing into a new Garden I was just invited to.

<img width="685" alt="Screen Shot 2021-06-09 at 3 18 00 PM" src="https://user-images.githubusercontent.com/1509695/121436822-1d2f7b00-c936-11eb-9109-1cce4a65ec2f.png">

**Comment by rrecuero** [comment]
Fixed
