### ISSUE TITLE
Trading Garden reserveAsset to itself leads to an error.

### ISSUE THREAD

**Issue by ylv-io** [babylon-finance/issues#74]
If you have DAI garden and want to lend DAI on compound it will revert with Receive token must be different. I assume it tries to trade DAI for DAI. I’ll look into this.
![image](https://user-images.githubusercontent.com/3285000/121701615-77038280-caa7-11eb-9872-f8efd6a776b8.png)

**Comment by rrecuero** [comment]
Fixed
