### ISSUE TITLE
Add DAI to wallet, refresh, still can't deposit even though wallet balance is sufficient

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#81]
I think this will be a pretty common pattern of events. To repro:
- Go to DAI garden with wallet that doesn't have enough DAI
- Try to deposit but realize not enough DAI
- Swap ETH for DAI in wallet
- Still can't deposit DAI
- Refresh page and click deposit, still can't deposit DAI even though have enough in wallet (see screenshot)
- Refresh again and it works, but you can deposit without clicking TOS (I think the TOS is a separate bug already being worked on)

<img width="1440" alt="Screen Shot 2021-06-11 at 5 36 00 PM" src="https://user-images.githubusercontent.com/1509695/121759698-e2674780-cadb-11eb-9fad-adc9de26b313.png">

<img width="831" alt="Screen Shot 2021-06-11 at 5 40 08 PM" src="https://user-images.githubusercontent.com/1509695/121759733-19d5f400-cadc-11eb-92a6-c8e2b028cb3f.png">

**Comment by rrecuero** [comment]
Fixed
