### ISSUE TITLE
Toast and Etherscan confirm transaction but modal keeps spinning

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#82]
When depositing into DAI garden (after approving) on Chrome with Metamask: 
- you get a toast and a modal saying your transaction is in progress
- but then the toast completes and the modal keeps spinning (it's confusing to have both notifications regardless imo)
- then if you click on the link to Etherscan it says transaction is complete but modal keeps spinning

I didn't have a chance to grab a screenshot, but hopefully easy to reproduce. Lmk if not and I can try again.

**Comment by undfined** [comment]
I see the issue, for some reason I added a 30 sec timeout to the receipt wait and it times out and returns a promise but we have to wait longer. I will remove it and it should work as expected.
