### ISSUE TITLE
Withdraw bug: shows wrong amount of receiving tokens

### ISSUE THREAD

**Issue by chaseadam17** [babylon-finance/issues#9]
Problem: shows the wrong amount of receiving tokens when withdrawing. Sometimes the amount of receiving tokens is empty, wrong amount, or flickers between different amounts.

Steps to reproduct:
1. Click withdraw
2. Edit amount of tokens to burn

Using Chrome Version 91.0.4472.77 (Official Build) (arm64)
Using Metamask (no HW)

Screenshots:
<img width="568" alt="Screen Shot 2021-06-04 at 12 42 30 PM" src="https://user-images.githubusercontent.com/1509695/120855286-1f0ece00-c533-11eb-877b-138a68efe51b.png">
<img width="606" alt="Screen Shot 2021-06-04 at 12 41 46 PM" src="https://user-images.githubusercontent.com/1509695/120855292-21712800-c533-11eb-96b8-b85fd4d50843.png">
<img width="597" alt="Screen Shot 2021-06-04 at 12 41 03 PM" src="https://user-images.githubusercontent.com/1509695/120855304-2504af00-c533-11eb-8454-9492e6d7641b.png">

**Comment by rrecuero** [comment]
done
